### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Smirnova1** [iben12/laravel-statable#5] opened 2019-03-22 00:09 UTC
Hi, thanks for the guide. But I ran into a problem. I did everything according to your documentation, but I always get an error Invalid argument supplied for foreach() in part .../SM/Factory/AbstractFactory.php
I get null when dd($this->configs)
my config file:
```

return [
    'status' => [
        'class' => App\Project::class,
        'graph' => 'status',
        'property_path' => 'status_id',
        'states' => [
            1, 2, 3, 4, 5, 6
        ],
        'transitions' => [
            'created' => [
                'from' => [1],
                'to' => 2,
            ],
            'success' => [
                'from' =>  [2],
                'to' => 3,
            ],
            'fail' => [
                'from' => [2],
                'to' => 4,
            ],
            'remove' => [
                'from' => [3, 4],
                'to' =>  5,
            ],
            'close' => [
                'from' => [3, 4],
                'to' =>  6,
            ],
        ],
        
        'callbacks' => [
            'history' => [
                'do' => 'StateHistoryManager@storeHistory'
            ]
        ],
    ],
];

```
I'm trying to call it:
````
use Statable;
    $project = Project::find(1);
    try {
            $project->apply('close');
        } catch (SMException $e) {
            abort(500, $e->getMessage()); 
        }
````
Why does this happen?

**Comment by iben12** [comment] 2019-03-22 08:22
Hi,

Could you please make sure if you properly set up your model class? It should look like this:
```
class Project extends Model
{
    use Statable;

    protected function getGraph()
    {
    	return 'status'; // the SM config to use
    }
}
```

The important part is the `getGraph` method, where you define which graph config will be used.

That's my first guess, hope it helps. If not, just come back and we'll try to figure it out.

**Comment by Smirnova1** [comment] 2019-03-23 09:49
Hi,
This method is implemented in my model. Unfortunately, I get the same error.

**Comment by Smirnova1** [comment] 2019-03-23 12:06
I solved this problem. 
I just cleared the cache.
php artisan cache:clear
php artisan config:clear
It worked for me.
Thank you for your work.

**Comment by iben12** [comment] 2019-03-23 12:09
Uhh, I just started typing "I'm sorry, I couldn't reproduce this error..."

I'm glad to hear that it is resolved. I close the issue.

**Closed as completed** 2019-03-23 12:10 UTC
